openapi: 3.0.0
info:
  title: MyLekarz API
  version: 1.0.0
  description: API Documentation for MyLekarz
servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://doc-web-rose.vercel.app/api
    description: Production server
paths:
  /patients:
    get:
      summary: Get all patients
      responses:
        '200':
          description: A list of patients
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: John Doe